# Generated by Django 5.0.4 on 2025-12-13 03:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.CharField(help_text='ユーザーの一意なID', max_length=36)),
                ('endpoint', models.URLField(max_length=512, unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('user_uuid', models.CharField(help_text='ユーザーの一意なID (主キー)', max_length=36, primary_key=True, serialize=False)),
                ('stripe_customer_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ユーザーの一意なID (myDeviceId)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='ユーザーが最初に登録された日時')),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripeの顧客ID', max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='StripeのサブスクリプションID', max_length=255, null=True)),
                ('subscription_status', models.CharField(default='incomplete', help_text='Stripeのサブスクリプションステータス', max_length=50)),
            ],
        ),
    ]
