# Generated by Django 5.0.4 on 2025-12-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0002_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('user_uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('stripe_customer_id', models.CharField(max_length=255, unique=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('subscription_status', models.CharField(default='incomplete', max_length=50)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
